version: '3'

services:
  drupal:
    container_name: drupal
#    image: gonzalomarin/drupal:latest
    image: drupal:10.0.1-apache
#    build: .
    restart: always
#    ports:
#     - 8081:80
    environment:
      DRUPAL_DATABASE_HOST: mariadb
      DRUPAL_DATABASE_PORT: 3306
      DRUPAL_DATABASE_NAME: drupal
      DRUPAL_DATABASE_USER: drupal
      DRUPAL_DATABASE_PASSWORD: drupal
    volumes:
      - drupal-data:/var/www/html
    depends_on:
      - mariadb
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: "true"
        fluentd-address: localhost:24224
        tag: drupal.logs

  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - mariadb-data:/var/lib/mysql

  haproxy:
     image: haproxy:1.6
     container_name: haproxy
     restart: always
     ports:
      - 8080:80
#      - 8443:4443
     volumes:
      - "./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"

  grafana:
     image: grafana/grafana
     container_name: grafana
     ports:
      - 3000:3000
     depends_on:
       - loki
     volumes:
     - ./grafana/configs/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml

  prometheus:
    image: prom/prometheus:v2.17.1
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
     - 9090:9090 

  node-exporter:
    image: prom/node-exporter:latest
    restart: always
    container_name: node-exporter
    ports:
      - "9100:9100"


volumes:
  mariadb-data:
  drupal-data:
  grafana-data:
  prometheus_data:
