version: '3'

services:
  drupal1:
    container_name: drupal1
    image: gonzalomarin/drupal:latest
    build: .
    restart: always
    environment:
      DRUPAL_DATABASE_HOST: mariadb
      DRUPAL_DATABASE_PORT: 3306
      DRUPAL_DATABASE_NAME: drupal
      DRUPAL_DATABASE_USER: drupal
      DRUPAL_DATABASE_PASSWORD: drupal
    volumes:
      - drupal-data:/var/www/html
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - mariadb-data:/var/lib/mysql

  haproxy:
     image: haproxy:1.6
     restart: always
     ports:
      - 8080:80
      - 8443:4443
     volumes:
      - "./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"


volumes:
  mariadb-data:
  drupal-data:
