version: '3'

services:
  drupal:
    image: drupal:9.4-php8.0-apache-bullseye
    restart: always
    volumes:
      - drupal-data:/opt/drupal/web/
    depends_on:
      - mariadb
    ports:
      - "8081-8082:80"
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: "true"
        fluentd-address: localhost:24224
        tag: drupal.logs

  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: user
      MYSQL_PASSWORD: clave
    volumes:
      - mariadb-data:/var/lib/mysql

  haproxy:
     image: haproxy:1.6
     container_name: haproxy
     restart: always
     ports:
      - 8080:80
     volumes:
      - "./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"

  grafana:
     image: grafana/grafana
     container_name: grafana
     ports:
      - 3000:3000
     depends_on:
       - loki
     volumes:
     - ./grafana/configs/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml

  prometheus:
    image: prom/prometheus:v2.17.1
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
     - 9090:9090

  loki:
    image: grafana/loki:2.0.0
    container_name: loki
    volumes:
      - ./config/loki.yaml:/etc/config/loki.yaml
    ports:
      - "3100:3100"

  fluentd:
    container_name: fluentd
    image: grafana/fluent-bit-plugin-loki
    ports:
      - 24224:24224
      - 24224:24224/udp
      - 2020:2020
      - 2021:2021
    environment:
      LOKI_URL: http://loki:3100/loki/api/v1/push
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf

  node-exporter:
    image: prom/node-exporter:latest
    restart: always
    container_name: node-exporter
    ports:
      - "9100:9100"


volumes:
  mariadb-data:
  drupal-data:
  grafana-data:
  prometheus_data:
  drupal-backup:
