global:
  scrape_interval: 30s

scrape_configs:

  - job_name: 'drupal'
    static_configs:
      - targets: ['drupal:80']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
