global:
  scrape_interval: 5s

scrape_configs:
  - job_name: fluentbit-exporter
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets: ["fluentd:2021"]

#  - job_name: mariadb
#    static_configs:
#      - targets: ["mariadb:9104"]
